# Generated by Django 3.0.6 on 2020-05-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('referral_count', models.IntegerField(default=1)),
                ('is_referenced', models.BooleanField(default=False)),
                ('referred_id', models.IntegerField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created_on')),
            ],
        ),
    ]
