# Generated by Django 3.0.6 on 2020-05-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='referred_id',
            field=models.IntegerField(null=True),
        ),
    ]
